### PR TITLE
Upgrade to hdf5 1.14.6 (breaks the image)

### PR DESCRIPTION
**Pull request by alfgrini75**
Update hdf5 to the newest version.

The 1.8 series are no longer supported  https://www.hdfgroup.org/2023/02/10/release-of-hdf5-1-8-23-newsletter-190/ 

@forderud I was not able to test this, and there is no pipeline here which checks that this works.

### CODE REVIEW

**Comment by forderud** [comment]
Build error when running `image\build_image.bat` locally:
```
 => [qtbuilder 22/27] RUN wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.6/hdf5-1.14.6.tar.gz   8.0s
 => [qtbuilder 23/27] WORKDIR /build/hdf5-1.14.6                                                                   0.0s
 => [qtbuilder 24/27] RUN emcmake cmake -S . -B build-wasm -DCMAKE_INSTALL_PREFIX:PATH=/opt/wasm-deps     -DHDF5  62.7s
 => [qtbuilder 25/27] WORKDIR /build/hdf5-1.14.6/build-wasm                                                        0.0s
 => ERROR [qtbuilder 26/27] RUN sed -i 's/js H5/js > H5/g' src/CMakeFiles/gen_hdf5-static.dir/build.make           0.4s
------
 > [qtbuilder 26/27] RUN sed -i 's/js H5/js > H5/g' src/CMakeFiles/gen_hdf5-static.dir/build.make:
0.344 sed: can't read src/CMakeFiles/gen_hdf5-static.dir/build.make: No such file or directory
------

 1 warning found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 128)
Dockerfile:66
--------------------
  64 |     WORKDIR /build/hdf5-1.14.6/build-wasm
  65 |     # Redirect the output of the binary to a file (it should use the 1st argument... But it doesn't)
  66 | >>> RUN sed -i 's/js H5/js > H5/g' src/CMakeFiles/gen_hdf5-static.dir/build.make
  67 |     RUN emmake make -j`nproc` install
  68 |
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c sed -i 's/js H5/js > H5/g' src/CMakeFiles/gen_hdf5-static.dir/build.make" did not complete successfully: exit code: 2
```

Error if also removing the "sed" line from Dockerfile:
```
/build/hdf5-1.14.6/src/H5Tinit_float.c:612:23: [ 69%] Building C object src/CMakeFiles/hdf5-static.dir/H5Torder.c.o
error: use of undeclared identifier 'FE_INVALID'
  612 |     if (feclearexcept(FE_INVALID) != 0)
      |                       ^
1 error generated.
```

Bug report: https://github.com/HDFGroup/hdf5/issues/4952 (fixed by https://github.com/HDFGroup/hdf5/pull/4954). This fix is unfortunately _not_ included in the HDF5 1.14.6 release.

**Comment by forderud** [comment]
The HDF5 regression have now been fixed by #88.

I've furthermore uploaded a new [`forderud/qtwasm:v6.9.3`](https://hub.docker.com/layers/forderud/qtwasm/v6.9.3) image to dockerhub that contains the HDF5 upgrade.
